
#ifndef _ArmProtocol_H_
#define _ArmProtocol_H_

#define ARM_PROTOCOL_QUIT 99
#define ARM_PROTOCOL_MOVE_TO_POINT 100
#define ARM_PROTOCOL_MOVE_JOINT_REL 110
#define ARM_PROTOCOL_MOVE_JOINT_ABS 111
#define ARM_PROTOCOL_REQUEST_CURRENT_POS 120
#define ARM_PROTOCOL_REQUEST_CURRENT_JOINTS 121
#define ARM_PROTOCOL_REQUEST_REQUIRED_JOINTS 122
#define ARM_PROTOCOL_MOVE_FREEZE 130
#define ARM_PROTOCOL_MOVE_MULTIPLE_JOINTS_ABS 116
#define ARM_PROTOCOL_ROTATION 140

#define ARM_GRIPPER_CLOSE 50
#define ARM_GRIPPER_OPEN 51
#define ARM_GRIPPER_SET_JOINT 52
#define ARM_GRIPPER_SOFT_CLOSE 53
#define ARM_GRIPPER_RELEASE 54

#endif

